plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'one.leaper.myproxy'
    compileSdk 37
    defaultConfig { minSdk 26 }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation project(':expo-modules-core')
    implementation files('libs/myproxy-network.aar')
}
